# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js image for building the project
FROM node:20-bookworm

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --ignore-scripts
RUN npx playwright install --with-deps chromium

COPY src ./src
COPY tsconfig.json ./

RUN npm run build

CMD ["npx", "-y", "supergateway", "--cors", "--healthEndpoint", "/health", "--stdio", "node dist/index.js", "--port", "8012"]